version: '3.7'

services:
clickhouse-server:
    image: learnclickhouse/public-repo:clickhouse-server-21.9
    container_name: clickhouse-server
    hostname: clickhouse-server
    ports:
    - "9000:9000"
    - "8123:8123"
    - "9009:9009"
    restart: always
    tty: true
    ulimits:
    memlock:
        soft: -1
        hard: -1
    nofile:
        soft: 262144
        hard: 262144
    cap_add:
    - IPC_LOCK


nginx-with-vector:
    image: learnclickhouse/public-repo:nginx-vector-21.9
    container_name: nginx-with-vector
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    - "8383:8383"
    #volumes:
    #  - ./nginx.conf:/etc/nginx/nginx.conf
    #  - './vector.toml:/vector/config/vector.toml'


