version: '3.7'

services:
clickhouse-server:
    image: learnclickhouse/public-repo:clickhouse-hackernews-21.10
    container_name: clickhouse-server
    hostname: clickhouse-server
    ports:
        - "9000:9000"
        - "8123:8123"
        - "9009:9009"
    # volumes:
    #   - ./my_config.xml:/etc/clickhouse-server/users.d/my_config.xml
    #   - ./remove_stopwords.py:/var/lib/clickhouse/user_scripts/remove_stopwords.py
    #   - ./log_query_config.xml:/etc/clickhouse-server/users.d/log_query_config.xml
    tty: true
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    cap_add:
    - IPC_LOCK
