apiVersion: apps/v1
kind: Deployment
metadata:
  name: service0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service0
  template:
    metadata:
      labels:
        app: service0
    spec:
      containers:
        - name: http-service0
          imagePullPolicy: Always
          image: ghongli/cncamp-cloudnative-httpserverv0:v1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service0
spec:
  selector:
    app: service0
  ports:
    - name: http-service0
      port: 80
      targetPort: 80
      protocol: TCP
