apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: http-server1
          imagePullPolicy: Always
          image: ghongli/cncamp-cloudnative-httpserverv1:v1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
    - name: http-server1
      port: 80
      targetPort: 80
      protocol: TCP